name: rijksbook
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  freezed_annotation:
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  mocktail:
  mocktail_image_network:

flutter:
  uses-material-design: true
